### ISSUE TITLE
Fresh install database error

### ISSUE THREAD

**Issue by Pierstoval** [Monofony/Monofony#516]
**Monofony version affected**: Latest as of this post

**Description**  

When installing a project (and fixing #515) , running the command `bin/console app:install` throws a database error:

```
❯ symfony console app:install -n

Installing AppName...
=====================



$$\      $$\                                $$$$$$\
$$$\    $$$ |                              $$  __$$\
$$$$\  $$$$ | $$$$$$\  $$$$$$$\   $$$$$$\  $$ /  \__|$$$$$$\  $$$$$$$\  $$\   $$\
$$\$$\$$ $$ |$$  __$$\ $$  __$$\ $$  __$$\ $$$$\    $$  __$$\ $$  __$$\ $$ |  $$ |
$$ \$$$  $$ |$$ /  $$ |$$ |  $$ |$$ /  $$ |$$  _|   $$ /  $$ |$$ |  $$ |$$ |  $$ |
$$ |\$  /$$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |     $$ |  $$ |$$ |  $$ |$$ |  $$ |
$$ | \_/ $$ |\$$$$$$  |$$ |  $$ |\$$$$$$  |$$ |     \$$$$$$  |$$ |  $$ |\$$$$$$$ |
\__|     \__| \______/ \__|  \__| \______/ \__|      \______/ \__|  \__| \____$$ |
                                                                        $$\   $$ |
                                                                        \$$$$$$  |
                                                                         \______/



Step 1 of 3. Setting up the database.
-------------------------------------

Creating AppName database for environment dev.
It appears that your database already exists.
Warning! This action will erase your database.
Seems like your database contains schema.
Warning! This action will erase your database.
 1/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 100%


Loading sample data for environment dev.
========================================


 [WARNING] This action will erase your database.


Cancelled loading sample data.


Step 2 of 3. Website configuration.
-----------------------------------

Create your administrator account.

In ExceptionConverter.php line 71:

  An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "sylius_admin_user" does not exist
  LINE 1: ...first_name_21, s0_.avatar_id AS avatar_id_22 FROM sylius_adm...
                                                               ^


In Exception.php line 28:

  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "sylius_admin_user" does not exist
  LINE 1: ...first_name_21, s0_.avatar_id AS avatar_id_22 FROM sylius_adm...
                                                               ^


In Statement.php line 130:

  SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "sylius_admin_user" does not exist
  LINE 1: ...first_name_21, s0_.avatar_id AS avatar_id_22 FROM sylius_adm...
                                                               ^


app:install:setup

The command terminated with an error code: 7.

In CommandExecutor.php line 46:

  The command terminated with an error code: 7.


app:install:setup
```

**Steps to reproduce**  

Fresh install, fix #515, start the containers with `docker compose up -d` and run `symfony console app:install -n`.

**Possible Solution**  

One of these two:

* Migrate the codebase to mysql (for now it's postgres)
* Add migrations for postgres (this means having **both** dbms migrations in the project)

**Comment by loic425** [comment]
@Pierstoval Don't use these Monofony packages anymore, it's deprecated, use Sylius stack instead.
https://stack.sylius.com/getting-started

Monofony will contains only features in Flex recipes in the future (with DDD architecture).

**Comment by loic425** [comment]
I've updated the README.
https://github.com/monofony/Monofony?tab=readme-ov-file#%EF%B8%8F-deprecated

**Comment by Pierstoval** [comment]
Thanks for clarifying this part 👍

Still not sure whether the new project I'm working on will use Sylius, I'm still working on the data model, but I will take a look at Sylius Stack 👍

**Comment by loic425** [comment]
> Thanks for clarifying this part 👍
> 
> Still not sure whether the new project I'm working on will use Sylius, I'm still working on the data model, but I will take a look at Sylius Stack 👍

Yes, of course.
Sylius stack is way better than Monofony was.
We still work on the documentation, but it's improving fast.
